GET http://localhost:8082/products HTTP/ 1.1
###

POST http://localhost:8082/products HTTP/1.1
Content-Type: application/json

{
    "productName": "cabo de internet",
    "category": "tecnologia",
    "price": 10.0
}

###

DELETE  http://localhost:8082/products/7d6bb612-03cd-441e-b8b6-98895cad84a5 HTTP/1.1
Content-Type: application/json